//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCodes
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string Diameter { get; set; }
        public string Length { get; set; }
        public string SignID { get; set; }
    }
}
